### ISSUE TITLE
Read the docs - automation not working.

### ISSUE THREAD

**Issue by kotaroyama** [cell2fire/Cell2Fire#99]
We have noticed that the changes we have made to our documentations aren't reflected on [our Read the Docs](https://cell2fire.readthedocs.io/en/latest/) .

 I've done a bit of investigation, and according to [this documentation](https://docs.readthedocs.io/en/stable/webhooks.html), Dave is the only one who can tweak the settings of this project.

TL;DR Dave is the only one who has access to readthedocs settings.

**Comment by DLWoodruff** [comment]
I tried adding a few more conditions under which it would do an update. It should do an update when I tag a release, which I will do next week. If that doesn't force an update, I will delete and rebuild the webhook.
